---

- name: Setup the LE audit
  include_tasks: LE_audit_setup.yml
  when:
      - setup_audit
  tags:
      - setup_audit

- name: "Ensure {{ audit_conf_dir }} exists"
  file:
      path: "{{ audit_conf_dir }}"
      state: directory
      mode: '0755'

- name: If using git for content set up
  block:
      - name: Install git
        package:
            name: git
            state: present
        vars:
            ansible_python_interpreter: "{{ python2_bin }}"

      - name: retrieve audit content files from git
        git:
            repo: "{{ rhel7cis_audit_file_git }}"
            dest: "{{ audit_conf_dir  }}"
            version: "{{ rhel7cis_audit_git_version }}"
  when:
      - audit_content == 'git'

- name: copy to audit content files to server
  copy:
      src: "{{ rhel7cis_audit_local_copy }}"
      dest: "{{ audit_conf_dir  }}"
      owner: root
      group: root
      mode: 0640
  when:
      - audit_content == 'copy'

- name: get audit content from url
  get_url:
      url: "{{ rhel7cis_audit_files_url }}"
      dest: "{{ audit_conf_dir  }}"
  when:
      - audit_content == 'get_url'

- name: Check Goss is available
  block:
      - name: Check for goss file
        stat:
            path: "{{ audit_bin }}"
        register: goss_available

      - name: Assert that goss is available
        assert:
            msg: "Audit has been selected: unable to find goss binary at {{ audit_bin }}"
        when:
            - not goss_available.stat.exists
  when:
      - run_audit

- name: Copy ansible default vars values to test audit
  template:
      src: ansible_vars_goss.yml.j2
      dest: "{{ audit_vars_path }}"
      mode: 0600
  when:
      - run_audit
  tags:
      - goss_template

- name: "Run pre_remediation {{ benchmark }} audit"
  goss:
      goss_path: "{{ audit_bin }}"
      path: "{{ goss_file }}"
      vars_path: "{{ audit_vars_path }}"
      format: "{{ audit_format }}"
      output_file: "{{ pre_audit_outfile }}"
  failed_when: false
  environment:
      GOSS_FMT_OPTIONS: Pretty

- name: Capture audit data if json format
  block:
      - name: "capture data {{ pre_audit_outfile }}"
        command: "cat {{ pre_audit_outfile }}"
        register: pre_audit
        changed_when: false

      - name: Capture pre-audit result
        set_fact:
            pre_audit_summary: "{{ pre_audit.stdout | from_json |json_query(summary) }}"
        vars:
            summary: 'summary."summary-line"'
  when:
      - audit_format == "json"

- name: Capture audit data if documentation format
  block:
      - name: "capture data {{ pre_audit_outfile }}"
        command: "tail -2 {{ pre_audit_outfile }}"
        register: pre_audit
        changed_when: false

      - name: Capture pre-audit result
        set_fact:
            pre_audit_summary: "{{ pre_audit.stdout_lines }}"
  when:
      - audit_format == "documentation"
